version: '3.9'

services:
  go-todo-app:
    container_name: go-todo-app
    image: shaleapps-challenge/go-todo-app:1.0.0
    build: .
    environment:
      DATABASE_URL: "postgres://postgres:postgres@go_todo_db:5432/postgres?sslmode=disable"
    ports:
      - "8000:8000"
    depends_on:
      - go_todo_db
  go_todo_db:
    container_name: go_todo_db
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:  
  pgdata: {}

networks:
  backend_network:
    driver: bridge
